version: "3.8"
services:
  pihole:
    container_name: pihole-penarol
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Montevideo'
      WEBPASSWORD: 'AndcarPihole'
    network_mode: "host"
    volumes:
      - /opt/pihole/pihole/:/etc/pihole/
      - /opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
