version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Montevideo'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - /opt/pihole/pihole/:/etc/pihole/
      - /opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
