version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Montevideo'
      WEBPASSWORD: ${WEBPASSWORD}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8088/80"
    volumes:
      - /opt/pihole/pihole/:/etc/pihole/
      - /opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
